version: "3.3"

services:
  traefik:
    container_name: mitm
    image: traefik:v2.9
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.certs:/certs:ro
      - ./conf.yml:/etc/traefik/dynamic_conf/conf.yml:ro
    command:
      --providers.file.directory=/etc/traefik/dynamic_conf
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.websecure.address=:443
      --entryPoints.websecure.http.tls=true
      --api.debug=true
      --api.dashboard=true
      --log.level=DEBUG
      --accesslog=true
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.rule: Host(`example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard.service: api@internal
    logging:
      driver: "json-file"
